### ISSUE TITLE
Interval value.

### ISSUE THREAD

**Issue by philipbaginski** [RobertBoes/nova-slider-field#3]
Hi! It looks like the interval value is hard coded and is at least 1. I tried to change it adding: ->interval(0.1) - nothing happened. I tried to change it in DetailField.vue file - nothing happened. What is the way to change Interval value to be 0.1?

Regards, Philip

**Comment by nalingia** [comment]
Hi @philipbaginski,
I got into the same issue. I looked into the code and, due to the `min`, `max` and `interval` input parameter types, setting decimal intervals in not possible at the moment. I've just proposed a PR with the fix to support decimal min, max and interval values: https://github.com/RobertBoes/nova-slider-field/pull/4.

I hope this could be merged into the master branch.

**Comment by philipbaginski** [comment]
Hi!

I have fixed it. Give me 1 hour and I will show you the place you have to change the code.
